### PR TITLE
updated Pipfile.lock

### PR DESCRIPTION
**Pull request by joe-gordian-software**
update Pipfile.lock in order to address https://github.com/metabolize/rq-dashboard-on-heroku/issues/16

### CODE REVIEW

**Comment by paulmelnikow** [comment]
Hi! Would love to get this fixed. Could you tell me how you generated the updated lockfile?

**Comment by paulmelnikow** [comment]
Hi @joe-gordian-software, just bumping this question! Would love to get this merged.

**Comment by joe-gordian-software** [comment]
hey @paulmelnikow sorry I missed this and I've forgotten how I did it.  I remember it was quite simple, like installing dependencies with pipenv and then committing the file

**Comment by joe-gordian-software** [comment]
closing as this is covered by #22

**Pull request closed without merging**
